package com.tecvuna.core.designsystem.resources.strings

interface IStringResources {
    val appName: String
    val welcomeMessage: String
    val getStarted: String
    val login: String
    val register: String
    val or: String
    val forgotPassword: String
    val createAccount: String
    val welcomeBack: String
    val signInWithGoogle: String
    val loginHeader: String
    val usernameHint: String
    val passwordHint: String
    val continueHint: String
    val createNewAccountHint: String
    val accountStatus: String
    val signUpOptionHeader: String
    val learnMore: String
    val buyer: String
    val farmer: String
    val alreadyHaveAnAccount: String
    val termsAndConditions: String
    val tellUsAboutYou: String
    val farmerDetails: String
    val farmerSellCrops: String
    val farmerShipMeans: String
    val buyerPickUpOrOrganized: String
    val productName: String
    val mango: String
    val apple : String
    val grapeFruit: String
    val waterMelon: String
    val pear: String
    val orange: String
    val banana: String
    val pineapple: String
    val cherry: String
    val avocado: String
    val buyerDetails: String
    val buyerNameCompanyQn: String
    val buyerCompanyNameHint: String
    val buyerCompanyDoQn: String
    val buyerCompanyDoHint: String
    val why: String
    val buyerShipReceiveMeanQn: String
    val personalDetail: String
    val tellUsAboutYourName: String
    val firstName: String
    val lastName: String
    val tellUsAboutYourLocation: String
    val streetInformation: String
    val regionProvince: String
    val zipCode: String
    val country: String
    val setUpAccount: String
    val loginDetails: String
    val enterYourEmailAddress: String
    val emailAddressHint: String
    val enterYourPhoneNumber: String
    val phoneNumberHint: String
    val enterYourPassword: String
    val reEnterYourPassword: String
    val oneLastStep: String
    val smsVerification: String
    val enterCode: String
    val resendCode: String
    val verify: String
    val whereToFindVerificationCode: String
    val successVerificationMessage: String
    val errorVerificationMessage: String
    val welcomeNote: String
    val done: String
    val total: String
    val farm: String
    val farms: String
    val productList: String
    val filter: String
    val farmSearchHint: String
    val farmOverviewTitle: String
    val farmItem: String
    val farmItems: String
    val newFarmTitle: String
    val farmDetails: String
    val productDetail : String
    val farmNameLabel: String
    val farmNameHint:String
    val farmAddressLabel: String
    val farmSizeLabel: String
    val farmSizeLabelHint: String
    val review: String
    val photos: String
    val farmerNameLabel: String
    val farmerNameLabelHint: String
    val pesticideUsed: String
    val wateringSystem: String
    val productNameLabelHint: String
    val productDescriptionLabel: String
    val productDescriptionHint: String
    val productTypeVarietyLabel: String
    val productTypeVarietyHint: String
    val productQuantityLabel: String
    val productQuantityHint: String
    val addButtonText: String
    val addProductTitle: String
    val addPesticideTitle: String
    val pesticideNameIdLabel: String
    val pesticideNameIdHint: String
    val productSprayed: String
    val addWateringSystem: String
    val productWatered: String
    val waterSystemNameIdLabel: String
    val waterSystemNameIdHint: String
    val record: String
    val edit: String
    val noteToSelf: String
    val vunatecNotification: String
    val options: String
    val delete: String
    val schedulePickUp: String
    val viewAsBuyer: String
    val paymentTitle: String
    val calenderTitle: String
    val dayOverview: String
    val calenderActivities: String
    val browseTitle: String
    val productSearchIdLabelHint: String
    val harvestSoon: String
    val browsingMenu: String
    val newProducts: String
    val shopLocal: String
    val buyAgain: String
    val soleBy: String
    val addToCart: String
    val editCart: String
    val cartTitle: String
    val subTotal: String
    val confirmButtonText: String
    val description: String
    val reviews: String
    val ready: String
    val verified: String
    val browsMenuTitle: String
    val accountMenuTitle: String
    val calendarMenuTitle: String
    val farmMenuTitle: String
    val dataMenuTitle: String
    val paymentMenuTitle: String
    val alertMenuTitle: String
    val today: String
    val thisWeek: String
    val tryAgain: String
    val trackYourOrder: String
    val notificationLoginMessage: String
    val invalidUsername: String
    val invalidPassword: String
    val invalidAddress: String
    val unknownError: String
    val wifiDisabled: String
    val requestFailed: String
    val noInternet: String
    val invalidPhoneNumber: String
    val invalidEmail: String
    val invalidFullName: String
    val pleaseLogin: String
    val securityTitle: String
    val securitySubtitle: String
    val changePasswordTitle: String
    val changePasswordSubTitle: String
    val aboutUsTitle: String
    val aboutUsSubTitle: String
    val termsAndPolicyTitle: String
    val termsAndPolicySubTitle: String
    val privacyAndPolicy: String
    val privacyAndPolicySubTitle: String
    val serviceCharter: String
    val serviceCharterSubTitle: String
    val dataCollectionSubTitle: String
    val dataCollectionTitle: String
    val changeLanguageTitle: String
    val changeLanguageSubTitle: String
    val supportTitle: String
    val supportSubTitle: String
    val callSupportTitle: String
    val callSupportSubTitle: String
    val emailTitle: String
    val emailSubTitle: String
    val emailSupport: String
    val twitterTitle : String
    val twitterSubTitle : String
    val chooseYourPreferredLanguage: String
    val home: String
    val nameLabel: String
    val nameHint: String
    val phoneNumberLabel: String
    val haveAnAccount: String
    val loginHint: String
    val dontHaveAnAccount: String
    val registerHint: String
    val searchHint: String
    val confirmOTPCodeTitle: String
    val confirmOTPDescription: String
    val haveSentConfirmationCode: String
    val resendVerificationCode: String
}
